# .github/release.yml

changelog:
  categories:
    - title: 🙌 Features
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: 😶 Dependencies
      labels:
        - dependencies
