name: Publish to NPM
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.11.1"

      - name: Install PNPM
        run: npm install -g pnpm@9.0.6
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfil
      - name: pnpm publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
