name: Publish to NPM
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.11.1"

      - name: Install PNPM
        run: npm install -g pnpm@9.0.6
      - name: Install dependencies
        run: pnpm install
      - name: npm publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
